server:
  port: 9999
spring:
  datasource: #Database
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3108
    url: jdbc:mysql://localhost:3306/webnews?createDatabaseIfNotExist=true
    #--------end database------------
  #Hibernate
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  #End hibernate
  thymeleaf:
    cache: false
logging:
  level:
    web: debug
